name: Node CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install testing dependencies
        run: npm i
      - name: test all apps and widgets
        run: npm run test
      - name: install typescript dependencies
        working-directory: ./typescript
        run: npm ci
      - name: build types
        working-directory: ./typescript
        run: npm run build:types
      - name: build all TS apps and widgets
        working-directory: ./typescript
        run: npm run build